name: ci

on:
  pull_request:

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - 'amazonlinux-1'
          - 'amazonlinux-2'
          - 'centos-7'
          - 'centos-8'
          - 'debian-9'
          - 'debian-10'
          - 'debian-11'
          - 'fedora-31'
          - 'fedora-32'
          - 'fedora-33'
          - 'fedora-latest'
          - 'opensuse-leap-15'
          - 'oraclelinux-7'
          - 'oraclelinux-8'
          - 'ubuntu-16.04'
          - 'ubuntu-18.04'
          - 'ubuntu-20.04'
          - 'ubuntu-20.10'
          - 'ubuntu-21.04'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build-date
        run: echo "::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        id: build-date
      - name: Short git sha
        run: echo "::set-output name=short::$(echo ${GITHUB_SHA} | cut -c1-8)"
        id: git-sha
      - name: Build Only
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          file: ./${{ matrix.os }}/Dockerfile
          build-args: |
            BUILD_DATE=${{ steps.build-date.outputs.build_date}}
            VCS_REF=${{ steps.git-sha.outputs.short }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
