name: build-and-push

on:
  pull_request:

jobs:
  buildx-arm64-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-with-arm64:
          - 'fedora-31'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build-date
        run: echo "::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        id: build-date
      - name: Short git sha
        run: echo "::set-output name=short::$(echo ${GITHUB_SHA} | cut -c1-8)"
        id: git-sha
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push (amd64, arm64)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            dokken/${{ matrix.os-with-arm64 }}:dev
          platforms: linux/amd64,linux/arm64
          file: ./${{ matrix.os-with-arm64 }}/Dockerfile
          build-args: |
            BUILD_DATE=${{ steps.build-date.outputs.build_date}}
            VCS_REF=${{ steps.git-sha.outputs.short }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
